apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 1 
  template: 
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: iad.ocir.io/idtat4ogmdyu/helloworld:latest
        volumeMounts: 
        - name: nfs
          mountPath: "/usr/share/demo"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: ocirsecret
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: oke-fsspvc
          readOnly: false
---
apiVersion: v1
kind: Service
metadata:
 name: helloworld
spec:
 type: LoadBalancer
 selector:
   app: helloworld
 ports:
   - name: client
     protocol: TCP
     port: 80
     nodePort: 32080
 selector:
   app: helloworld
