apiVersion: v1
kind: PersistentVolume
metadata:
  name: oke-fsspv
spec:
  storageClassName: oci-fss
  capacity:
   storage: 100Gi
  accessModes:
   - ReadWriteMany
  mountOptions:
   - nosuid
  nfs:
    server: 10.0.2.3
    path: "/fileSystemDemo"
    readOnly: false                            
